# Default values for aks-state-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

## The number of Pods, which are created by the Deployment.
## See: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
##
replicaCount: 1

## Specify a list of image pull secrets, to avoid the DockerHub rate limit or to pull the aks-state-exporter image from
## a private registry.
## See: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []

## Set the image which should be used for aks-state-exporter.
##
image:
  repository: ghcr.io/ricoberger/aks-state-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

## Specify security settings for the created Pods. To set the security settings for the aks-state-exporter Container use
## the corresponding "securityContext" field.
## See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
podSecurityContext: {}
  # fsGroup: 2000

## Specify security settings for the aks-state-exporter Container. They override settings made at the Pod level via the
## "podSecurityContext" when there is overlap.
## See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
##
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## We usually recommend not to specify default resources and to leave this as a conscious choice for the user. This
## also increases chances charts run on environments with little resources, such as Minikube. If you do want to
## specify resources, uncomment the following lines, adjust them as necessary, and remove the curly braces after
## 'resources:'.
##
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Specify a map of key-value pairs, to assign the Pods to a specific set of nodes.
## See: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
##
nodeSelector: {}

## Specify the tolerations for the aks-state-exporter Pods.
## See: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
##
tolerations: []

## Specify a node affinity or inter-pod affinity / anti-affinity for an advanced scheduling of the aks-state-exporter
## Pods.
## See: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Topology spread constraints rely on node labels to identify the topology domain(s) that each Node is in.
## See: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
##
topologySpreadConstraints: []
  # - maxSkew: 1
  #   topologyKey: topology.kubernetes.io/zone
  #   whenUnsatisfiable: DoNotSchedule
  #   labelSelector:
  #     matchLabels:
  #       app.kubernetes.io/name=hub

## Specify additional volumes for the aks-state-exporter deployment.
## See: https://kubernetes.io/docs/concepts/storage/volumes/
##
volumes: []

## Specify additional volumeMounts for the aks-state-exporter container.
## See: https://kubernetes.io/docs/concepts/storage/volumes/
##
volumeMounts: []

## Specify additional environment variables for the aks-state-exporter container.
##
env: []
  # - name: AZURE_SUBSCRIPTION_ID
  #   value: MY_ENV_VALUE
  # - name: AZURE_TENANT_ID
  #   value: MY_ENV_VALUE
  # - name: AZURE_CLIENT_ID
  #   value: MY_ENV_VALUE
  # - name: AZURE_CLIENT_SECRET
  #   value: MY_ENV_VALUE

## Specify additional labels and annotations for the created Pods.
##
podAnnotations: {}
podLabels: {}

## Set the type for the created service: ClusterIP, NodePort, LoadBalancer.
## See: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
##
service:
  type: ClusterIP

  annotations: {}
  labels: {}

serviceAccount:
  name: ""

## Create a Service Monitor for the Prometheus Operator.
## See: https://github.com/coreos/prometheus-operator
##
serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a Prometheus Operator
  ##
  enabled: false
  additionalMetricsRelabels: {}
  additionalRelabeling: []
  labels: {}
  path: /metrics
  interval: 30s
  scrapeTimeout: 30s

## The configuration for the aks-state-exporter
##
config: |
  exporter:
    aks:
      credentials:
        subscriptionID: $AZURE_SUBSCRIPTION_ID
        tenantID: $AZURE_TENANT_ID
        clientID: $AZURE_CLIENT_ID
        clientSecret: $AZURE_CLIENT_SECRET
      resourceGroups:
        - dev-de1
        - stage-de1
        - prod-de1
