apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aks-state-exporter.fullname" . }}
  labels:
    {{- include "aks-state-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ tpl .Values.config . | indent 4 }}
