{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "aks-state-exporter.labels" . | nindent 4 }}
    {{- include "aks-state-exporter.serviceMonitorLabels" . | nindent 4 }}
  name: {{ include "aks-state-exporter.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.serviceMonitor.namespace }}
spec:
  endpoints:
    - port: http
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      path: /metrics
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
      {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
      {{ toYaml . | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "aks-state-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
