apiVersion: v1
kind: Service
metadata:
  name: {{ include "aks-state-exporter.fullname" . }}
  labels:
    {{- include "aks-state-exporter.labels" . | nindent 4 }}
    {{- include "aks-state-exporter.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "aks-state-exporter.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aks-state-exporter.selectorLabels" . | nindent 4 }}
